chain:
  bech32_prefix: rarimo
  modules:
    - modules
    - messages
    - auth
    - bank
    - gov
    - mint
    - slashing
    - staking
    - distribution
node:
  type: "remote"
  config:
    rpc:
      client_name: rarimo
      address: http://localhost:26657
      max_connections: 20
    grpc:
      address: http://localhost:9090
      insecure: true
parsing:
  workers: 1
  listen_new_blocks: true
  parse_old_blocks: true
  parse_genesis: true
  start_height: 1
  fast_sync: true
  average_block_time: 3s
  genesis_file_path: .bdjuno/genesis.json
database:
  name: bdjuno-db
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  schema: public
  max_open_connections: 10
  max_idle_connections: 10
  partition_size: 100000
  partition_batch: 1000
logging:
  level: debug
  format: text
actions:
  port: 3000
